all:

  children:

    loadbalancer:

      hosts:

        nginx-lb:
          ansible_host: 3.27.88.111
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/platform-cloud-key.pem

    web:

      hosts:

        web01:
          ansible_host: 3.27.147.54
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/platform-cloud-key.pem

        web02:
          ansible_host: 15.135.213.181
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/platform-cloud-key.pem
