---
- name: Tenant Infrastructure PreCheck

  hosts: localhost
  gather_facts: false

  tasks:

    - name: Display Region
      debug:
        var: region

    - name: Verify Region Exists
      assert:
        that:
          - region is defined
          - region | length > 0
        fail_msg: "Region missing"

    - name: Infrastructure Ready
      debug:
        msg: "PreCheck Passed"
