---
- name: Tenant Infrastructure PreCheck
  hosts: localhost
  gather_facts: false

  tasks:

    - name: Show Region Value
      debug:
        var: region

    - name: Verify Region
      assert:
        that:
          - region in allowed_regions
        fail_msg: "Unsupported Region"

    - name: Infrastructure PreCheck Passed
      debug:
        msg: "Infrastructure is ready for provisioning"
