  tasks:

    - name: Display Complete Service Request
      debug:
        var: service_request

    - name: Validate Tenant Name
      assert:
        that:
          - service_request.tenant.name | length > 2
        fail_msg: "Tenant Name cannot be empty"

    - name: Validate Region
      assert:
        that:
          - service_request.tenant.region in [
              'CHN-SPD-MAA01',
              'MUM-PNL-BOM01',
              'MUM-MPE-BOM02'
            ]
        fail_msg: "Unsupported Region"

    - name: Validate Environment
      vars:
        valid_envs:
          - Development
          - Testing
          - UAT
          - Production
      assert:
        that:
          - service_request.tenant.environment in valid_envs
        fail_msg: "Unsupported Environment"

    - name: Service Request Validation Successful
      debug:
        msg: "Tenant Service Request has been validated successfully."
